config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms
  resources :posts
  root 'posts#index'
  resources :users
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
    has_many :posts, dependent: :destroy
    validates :name, presence: true
    validates :profile, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user!

    def new
        @post = Post.new
    end

    def index
        if params[:search] == nil
            @posts= Post.all
        elsif params[:search] == ''
            @posts= Post.all
        else
            #部分検索
            @posts = Post.where("time LIKE ? ",'%' + params[:search] + '%')
        end
    end

    def create
        post = Post.new(post_params)

        post.user_id = current_user.id 

        if post.save
            redirect_to :action =>"index"
        else
            redirect_to :action =>"new"
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        post = Post.find(params[:id])
        if post.update(post_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
    end

    private
    def post_params
        params.require(:post).permit(:time,:day,:room,:about)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roomsearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li><% if user_signed_in? %>
          <%= link_to "ホーム", posts_path %>
          <%= link_to "新規投稿",new_post_path %>
          <%= link_to "マイページへ", user_path(current_user.id) %>
          <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
        <% end %>
        </li>
      </ul>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>
      <p>Copyright © MK All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/posts/edit.html.erb
<%= stylesheet_link_tag 'edit', :media => "all" %>

<div class="henshu">
    <h3>編集ページ</h3>
    <br>
    <h4>about には教室についての追加情報の内容を<br>記述してください。<br>（例）授業変更により空き教室ではなくなりました。</h4>
    <br>
    <%= form_for @post do |f| %>
        <%= f.label :time  %>
        <%= f.select :time, 
        [["月 1限", "月 1限"],
        ["月 2限", "月 2限"], 
        ["月 3限", "月 3限"],
        ["月 4限", "月 4限"],
        ["月 5限", "月 5限"],
        ["火 1限", "火 1限"], 
        ["火 2限", "火 2限"],
        ["火 3限", "火 3限"],
        ["火 4限", "火 4限"],
        ["火 5限", "火 5限"],
        ["水 1限", "水 1限"],
        ["水 2限", "水 2限"],
        ["水 3限", "水 3限"],
        ["水 4限", "水 4限"],
        ["水 5限", "水 5限"],
        ["木 1限", "木 1限"],       
        ["木 2限", "木 2限"],
        ["木 3限", "木 3限"],
        ["木 4限", "木 4限"],
        ["木 5限", "木 5限"], 
        ["金 1限", "金 1限"], 
        ["金 2限", "金 2限"],
        ["金 3限", "金 3限"],
        ["金 4限", "金 4限"],
        ["金 5限", "金 5限"],
        ["土 1限", "土 1限"],
        ["土 2限", "土 2限"],
        ["土 3限", "土 3限"],
        ["土 4限", "土 4限"],
        ["土 5限", "土 5限"]], include_blank: "選択して下さい" %>
        </br>
        <%= f.label :room %>
        <%= f.text_field :room, :size => 30 %>
        </br>
        <%= f.label :about  %>
        <%= f.text_area :about, :size => "30x2" %>
        </br>
        <%= f.submit "編集する" %>
    <% end %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<div class="dekai">
  <div class="oolong">
    <h1>立教大<br> 空教室</h1>
    <h3>投稿を検索</h3>
    <div class="kensaku">
      <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
      <%= text_field_tag :search %>
      <%= submit_tag '検索する'  %>
    </div>
    <h5>例：月 1限</h5>
    <% end %>
  </div>

  <div class="posts-container">
  <h3>一覧ページ</h3>
    <% @posts.each do |t| %>
      <div class="post">
        <div class="namebox">
          <%= t.time %>
          &emsp;
          <%= link_to t.user.name, user_path(t.user.id) %>
        </div>
        <div class="main-box">
          <%= t.room %>
          <%= link_to "詳細へ", post_path(t.id) %>
          <% if user_signed_in? && current_user.id == t.user_id %>
          <%= link_to "編集する", edit_post_path(t.id) %>
          <%= button_to "削除する", post_path(t.id), method: :delete %>
          <% end %> 
        </div>
        <div class="aboutbox">
          <%= t.about %>
          <br>
          <%= t.created_at.to_s(:datetime_jp) %>
        </div>
      </div>
    <% end %>
  </div>
</div> 

app/views/posts/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="shin">
    <h2>新規投稿ページ</h2>
    <br>
    <h4>about には教室についての<br>追加情報の内容を記述してください。<br>（例）授業変更で空き教室ではなくなりました。</h4>
    <br>
    <%= form_for @post do |f| %>
    
        <div class="field">
            <%= f.label :time  %>
            <%= f.select :time, 
            [["月 1限", "月 1限"],
            ["月 2限", "月 2限"], 
            ["月 3限", "月 3限"],
            ["月 4限", "月 4限"],
            ["月 5限", "月 5限"],
            ["火 1限", "火 1限"], 
            ["火 2限", "火 2限"],
            ["火 3限", "火 3限"],
            ["火 4限", "火 4限"],
            ["火 5限", "火 5限"],
            ["水 1限", "水 1限"],
            ["水 2限", "水 2限"],
            ["水 3限", "水 3限"],
            ["水 4限", "水 4限"],
            ["水 5限", "水 5限"],
            ["木 1限", "木 1限"],       
            ["木 2限", "木 2限"],
            ["木 3限", "木 3限"],
            ["木 4限", "木 4限"],
            ["木 5限", "木 5限"], 
            ["金 1限", "金 1限"], 
            ["金 2限", "金 2限"],
            ["金 3限", "金 3限"],
            ["金 4限", "金 4限"],
            ["金 5限", "金 5限"],
            ["土 1限", "土 1限"],
            ["土 2限", "土 2限"],
            ["土 3限", "土 3限"],
            ["土 4限", "土 4限"],
            ["土 5限", "土 5限"]], include_blank: "選択して下さい" %>
        <div>

        <div class="field">
            <%= f.label :room %>
            <%= f.text_field :room, :size => 30 %>
        </div>

        <div class="field">
            <%= f.label :about  %>
            <%= f.text_area :about, :size => "30x2" %>
        </div>

        <%= f.submit "投稿する" %>
    <% end %>

    <%= link_to "一覧に戻る", posts_path %>
</div>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>

<div class="shosai">
  <h3>詳細</h3>
  <div class="post">
    <p><%= @post.time %></p>
    <p><%= @post.room %></p>
    <p><%= @post.about %></p>
  </div>

  <%= link_to "一覧に戻る", posts_path %>
  <%= link_to "編集する", edit_post_path(@post.id) %>
</div>  

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'usershow', :media => "all" %>

<div class="johou">
  <h3>user情報</h3>
  <p>名前 : <%= @user.name %></p>
  <p>メールアドレス : <%= @user.email %></p>
  <p>プロフィール : <%= @user.profile %></p>

  <% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_registration_path %>
  <% end %>

  <h3>userの投稿</h3>
    <% @user.posts.each do |t| %>
      <div class="usershow">
        <%= t.time %>
        <%= t.room %>
        <%= t.about %>
      <% end %>
    </div>

  <%= link_to "一覧に戻る", posts_path %>
</div>